Use 'quill sns' instead of 'sns-quill'. (#85)
# Motivation

I'm trying to make snsdemo work on my M1 Mac for local testing.
sns-quill is giving me
```
Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
```
For other tools that gave this error, I replaced them with version that
have openssl statically linked, but I couldn't find one for sns-quill
and supposedly sns-quill functionality is now provided by `quill sns`.
However, snsdemo was still using the old swap flow with a single
command, which is not supported by `quill sns`.

Also, `quill sns pay` takes an amount in e8s while `sns-quill` takes an
amount in whole ICP.

# Changes

1. Remove installation of `sns-quill` from `dfx-sns-demo-install`.
2. Delete `bin/dfx-software-sns-quill-install`.
3. Use `quill sns` for creating the message and `quill send` for sending
the message instead of using `sns-quill`.
4. Move sending the message from `dfx-sns-sale-buy` to `dfx-sns-quill`.
5. Make separate `quill sns new-sale-ticket` and `quill sns pay` calls.
6. Convert the amount passed to dfx-sns-sale-buy to e8s, or if `max` is
passed, no longer convert from e8s.

diff --git a/bin/dfx-sns-quill b/bin/dfx-sns-quill
--- a/bin/dfx-sns-quill
+++ b/bin/dfx-sns-quill
@@ -16,7 +16,7 @@ export DFX_NETWORK
 
 # If no subcommand has been provided, list all subcommands.
 (($# > 0)) || {
-  sns-quill --help | sed -n '/^SUBCOMMANDS:/,$p'
+  quill sns --help | sed -n '/^SUBCOMMANDS:/,$p'
   exit 1
 }
 
@@ -27,7 +27,24 @@ dfx-sns-quill-canister-ids --network "$DFX_NETWORK" >"$SNS_QUILL_CANISTER_IDS_FI
 PEM_PATH="$(dfx-identity-pem --identity "$DFX_IDENTITY")"
 
 # Call sns-quill
-sns-quill --canister-ids-file "$SNS_QUILL_CANISTER_IDS_FILE" --pem-file "$PEM_PATH" "${@}"
+set quill sns --canister-ids-file "$SNS_QUILL_CANISTER_IDS_FILE" --pem-file "$PEM_PATH" "${@}"
+echo "${@}"
+MESSAGE="$("${@}")"
 
 # Tidy up.
 rm "$SNS_QUILL_CANISTER_IDS_FILE"
+
+test -n "${MESSAGE:-}" || {
+  echo "ERROR: Empty message"
+  exit 1
+} >&2
+
+# Set the URL used by quill
+IC_URL="$("$SOURCE_DIR/dfx-network-url" --network "$DFX_NETWORK")"
+
+echo "$MESSAGE" | IC_URL="$IC_URL" quill send --insecure-local-dev-mode - --yes || {
+  echo "ERROR: Failed to send message."
+  echo "Message:"
+  echo "$MESSAGE"
+  exit 1
+}
