Prettier test

diff --git a/bin/dfx-stock-test b/bin/dfx-stock-test
--- a/bin/dfx-stock-test
+++ b/bin/dfx-stock-test
@@ -28,5 +28,23 @@ export DFX_NETWORK
 
 (
   print_title "sns_aggregator should be installed"
-  curl --retry 5 --fail "$(dfx-canister-url sns_aggregator)" | grep -q "The aggregator collects information on all deployed SNS"
+  index_html="$(mktemp --suffix .html index_XXXX)"
+  curl --silent --retry 5 --fail "$(dfx-canister-url sns_aggregator)" >"$index_html" || {
+    echo "ERROR: Should be able to get sns_aggregator home page."
+    exit 1
+  } >&2
+  expected_in_index="The aggregator collects information on all deployed SNS"
+  grep -q "$expected_in_index" "$index_html" || {
+    echo "ERROR: The aggregator home page should include the expected text."
+    echo "       - The home page may have changed; if so please update the expected text."
+    echo "       - The attempt to retrieve the home page may have got an error page or"
+    echo "         blank response.  If so, please make sure that the aggregator is"
+    echo "         installed correctly."
+    echo "EXPECTED TO FIND: '$expected_in_index'"
+    echo "IN PAGE CONTENT:"
+    cat "$index_html"
+    exit 1
+  } >&2
 )
+
+echo "$(basename "$0") PASSED"
