Support raw for static URLs only

diff --git a/bin/dfx-canister-url b/bin/dfx-canister-url
--- a/bin/dfx-canister-url
+++ b/bin/dfx-canister-url
@@ -64,7 +64,7 @@ URL_TYPES=(static api)
 clap.define short=n long=network desc="The dfx network to use" variable=DFX_NETWORK default="local"
 clap.define short=c long=canister desc="The canister name" variable=DFX_CANISTER
 clap.define short=t long=type desc="The canister type (options: ${URL_TYPES[*]})" variable=DFX_URL_TYPE default=static
-clap.define short=r long=raw desc="Provide a raw URL" variable=DFX_RAW nargs=0 default=""
+clap.define short=r long=raw desc="Provide a raw static URL" variable=DFX_RAW nargs=0 default=""
 clap.define short=o long=open desc="Open the URL in a browser" variable=DFX_OPEN nargs=0
 # Source the output file ----------------------------------------------------------
 source "$(clap.build)"
@@ -77,6 +77,11 @@ printf '%s\0' "${URL_TYPES[@]}" | grep -Fxqz -- "$DFX_URL_TYPE" || {
   echo "ERROR: Unsupported URL type: '$DFX_URL_TYPE'"
   echo "       Valid options:"
   printf "       * %s\n" "${URL_TYPES[@]}"
+  exit 1
+} >&2
+[[ "${DFX_RAW:-}" != "true" ]] || [[ "$DFX_URL_TYPE" == "static" ]] || {
+  echo "ERROR:  As far as I know, there are no properly supported raw API URLs."
+  echo "        If you know otherwise, please share."
   exit 1
 } >&2
 
