Updating frontend formatting

diff --git a/bin/dfx-canister-url b/bin/dfx-canister-url
--- a/bin/dfx-canister-url
+++ b/bin/dfx-canister-url
@@ -9,7 +9,7 @@ testnet=""
 ic_repo="$HOME/dfn/ic"
 
 print_help() {
-	cat <<-EOF
+  cat <<-EOF
 		Prints the NNS URL of a testnet or local dfx.
 
 		This is useful for:
@@ -38,73 +38,73 @@ print_help() {
 }
 
 while (($# > 0)); do
-	arg="$1"
-	shift 1
-	case "$arg" in
-	--help)
-		print_help
-		exit 0
-		;;
-	--ic-repo)
-		ic_repo="$1"
-		shift 1
-		;;
-	--open)
-		command=xdg-open                      # Uses Linux default browser
-		command -v "$command" || command=open # Uses mac default browser
-		command -v "$command" || command=firefox
-		command -v "$command" || command=google-chrome
-		command -v "$command" || {
-			printf "ERROR: %s\n" "Unable to detect how to open your browser."
-			exit 1
-		} >&2
-		;;
-	--testnet)
-		testnet="$1"
-		shift 1
-		;;
-	--dfx-network)
-		DFX_NETWORK="$1"
-		shift 1
-		;;
-	*)
-		{
-			printf "ERROR: %s '%s'\n" "Unknown argument:" "$arg"
-			printf "Usage:"
-			print_help
-		} >&2
-		exit 1
-		;;
-	esac
+  arg="$1"
+  shift 1
+  case "$arg" in
+  --help)
+    print_help
+    exit 0
+    ;;
+  --ic-repo)
+    ic_repo="$1"
+    shift 1
+    ;;
+  --open)
+    command=xdg-open                      # Uses Linux default browser
+    command -v "$command" || command=open # Uses mac default browser
+    command -v "$command" || command=firefox
+    command -v "$command" || command=google-chrome
+    command -v "$command" || {
+      printf "ERROR: %s\n" "Unable to detect how to open your browser."
+      exit 1
+    } >&2
+    ;;
+  --testnet)
+    testnet="$1"
+    shift 1
+    ;;
+  --dfx-network)
+    DFX_NETWORK="$1"
+    shift 1
+    ;;
+  *)
+    {
+      printf "ERROR: %s '%s'\n" "Unknown argument:" "$arg"
+      printf "Usage:"
+      print_help
+    } >&2
+    exit 1
+    ;;
+  esac
 done
 
 test -n "${DFX_NETWORK:-}" || test -n "${testnet:-}" || {
-	DFX_NETWORK="local"
+  DFX_NETWORK="local"
 }
 
 if test -n "${DFX_NETWORK:-}" && [[ "$DFX_NETWORK" != "local" ]]; then
-	DFX_NETWORK="$DFX_NETWORK" jq -er '.networks[env.DFX_NETWORK].providers[0]' dfx.json
+  DFX_NETWORK="$DFX_NETWORK" jq -er '.networks[env.DFX_NETWORK].providers[0]' dfx.json
 elif test -n "${testnet:-}"; then
-	testnet_config_dir="${ic_repo}/testnet/env/$testnet/"
-	test -d "$ic_repo" || {
-		printf "ERROR: %s '%s'\n" "IC repo directory does not exist:" "$ic_repo"
-		exit 1
-	} >&2
-	test -d "$testnet_config_dir" || {
-		printf "ERROR: %s '%s'\n" "Testnet config directory does not exist:" "$testnet_config_dir"
-		exit 1
-	} >&2
-	"$command" "http://[$(cd "$testnet_config_dir" && ./hosts --nns-nodes | awk '{print $2 ; exit 0}')]:8080"
+  testnet_config_dir="${ic_repo}/testnet/env/$testnet/"
+  test -d "$ic_repo" || {
+    printf "ERROR: %s '%s'\n" "IC repo directory does not exist:" "$ic_repo"
+    exit 1
+  } >&2
+  test -d "$testnet_config_dir" || {
+    printf "ERROR: %s '%s'\n" "Testnet config directory does not exist:" "$testnet_config_dir"
+    exit 1
+  } >&2
+  "$command" "http://[$(cd "$testnet_config_dir" && ./hosts --nns-nodes | awk '{print $2 ; exit 0}')]:8080"
 else
-	local_dfx_port_file="$PWD/.dfx/replica-configuration/replica-1.port"
-	port="$(cat "$local_dfx_port_file" || true)"
-	url="http://localhost:${port}"
-	# Yes, shell does not bind logical operators like some other languages.  That is fine.
-	# Thank you, shellcheck, for making sure that we are aware.
-	# shellcheck disable=SC2015
-	test -e "$local_dfx_port_file" && curl -s "$url" >/dev/null || {
-		printf "ERROR: %s\n" "dfx does not appear to be running in this repo"
-		exit 1
-	} >&2
-	"$command" "$url"
+  local_dfx_port_file="$PWD/.dfx/replica-configuration/replica-1.port"
+  port="$(cat "$local_dfx_port_file" || true)"
+  url="http://localhost:${port}"
+  # Yes, shell does not bind logical operators like some other languages.  That is fine.
+  # Thank you, shellcheck, for making sure that we are aware.
+  # shellcheck disable=SC2015
+  test -e "$local_dfx_port_file" && curl -s "$url" >/dev/null || {
+    printf "ERROR: %s\n" "dfx does not appear to be running in this repo"
+    exit 1
+  } >&2
+  "$command" "$url"
 fi
diff --git a/bin/dfx-network-deploy-config b/bin/dfx-network-deploy-config
--- a/bin/dfx-network-deploy-config
+++ b/bin/dfx-network-deploy-config
@@ -7,8 +7,8 @@ source "$SOURCE_DIR/optparse.bash"
 # Define options
 optparse.define short=n long=network desc="The dfx network to use" variable=DFX_NETWORK default="local"
 optparse.define short=c long=commit desc="The IC commit of the wasms" variable=IC_COMMIT default="$(
-	. "$SOURCE_DIR/versions.bash"
-	echo "$IC_COMMIT"
+  . "$SOURCE_DIR/versions.bash"
+  echo "$IC_COMMIT"
 )"
 optparse.define short=x long=ic_dir desc="Directory containing the ic source code" variable=IC_REPO_DIR default="$HOME/dfn/ic"
 optparse.define short=y long=nd_dir desc="Directory containing the nns-dapp source code" variable=ND_REPO_DIR default="$HOME/dfn/nns-dapp"
@@ -19,29 +19,29 @@ set -euo pipefail
 export DFX_NETWORK
 
 if [[ "$DFX_NETWORK" == "local" ]]; then
-	# Run locally; can be configured by e.g. chnaging the wasm files in the cache
-	dfx-network-stop --network "$DFX_NETWORK"
-	dfx start --clean
-	dfx nns deploy
+  # Run locally; can be configured by e.g. chnaging the wasm files in the cache
+  dfx-network-stop --network "$DFX_NETWORK"
+  dfx start --clean
+  dfx nns deploy
 else
-	# Run remotely with one of the predefined configurations.
-	# Note: This is still relatively slow and error prone.  Points of friction need to be ironed
-	# out before we can resonably ask people to do this.
-	IC_REPO_DIR="${IC_REPO_DIR:-$HOME/dfn/ic-github/}"
-	ND_REPO_DIR="${ND_REPO_DIR:-$HOME/dfn/nns-dapp/}"
-	TESTNET="$DFX_NETWORK"
-	test -d "$ND_REPO_DIR" || {
-		echo "Invalid directory for nns-dapp source code: $ND_REPO_DIR"
-		exit 1
-	} >&2
-	(
-		set -euxo pipefail
-		echo "Configuring NNS..."
-		DFX_IDENTITY="$(dfx identity whoami)"
-		dfx identity use ident-1
-		dfx-nns-propose xdr-icp-conversion-rate --network "$DFX_NETWORK"
-		dfx-nns-propose to-set-authorized-subnetworks --network "$DFX_NETWORK"
-		dfx-sns-subnet-add --network "$DFX_NETWORK" --identity test
-		dfx identity use "$DFX_IDENTITY"
-	)
+  # Run remotely with one of the predefined configurations.
+  # Note: This is still relatively slow and error prone.  Points of friction need to be ironed
+  # out before we can resonably ask people to do this.
+  IC_REPO_DIR="${IC_REPO_DIR:-$HOME/dfn/ic-github/}"
+  ND_REPO_DIR="${ND_REPO_DIR:-$HOME/dfn/nns-dapp/}"
+  TESTNET="$DFX_NETWORK"
+  test -d "$ND_REPO_DIR" || {
+    echo "Invalid directory for nns-dapp source code: $ND_REPO_DIR"
+    exit 1
+  } >&2
+  (
+    set -euxo pipefail
+    echo "Configuring NNS..."
+    DFX_IDENTITY="$(dfx identity whoami)"
+    dfx identity use ident-1
+    dfx-nns-propose xdr-icp-conversion-rate --network "$DFX_NETWORK"
+    dfx-nns-propose to-set-authorized-subnetworks --network "$DFX_NETWORK"
+    dfx-sns-subnet-add --network "$DFX_NETWORK" --identity test
+    dfx identity use "$DFX_IDENTITY"
+  )
 fi
diff --git a/bin/dfx-network-deploy-testnet b/bin/dfx-network-deploy-testnet
--- a/bin/dfx-network-deploy-testnet
+++ b/bin/dfx-network-deploy-testnet
@@ -7,8 +7,8 @@ source "$SOURCE_DIR/optparse.bash"
 # Define options
 optparse.define short=n long=network desc="The dfx network to use" variable=DFX_NETWORK default="local"
 optparse.define short=c long=commit desc="The IC commit of the wasms" variable=IC_COMMIT default="$(
-	. "$SOURCE_DIR/versions.bash"
-	echo "$IC_COMMIT"
+  . "$SOURCE_DIR/versions.bash"
+  echo "$IC_COMMIT"
 )"
 optparse.define short=x long=ic_dir desc="Directory containing the ic source code" variable=IC_REPO_DIR default="$HOME/dfn/ic"
 optparse.define short=y long=nd_dir desc="Directory containing the nns-dapp source code" variable=ND_REPO_DIR default="$HOME/dfn/nns-dapp"
@@ -19,34 +19,34 @@ set -euo pipefail
 export DFX_NETWORK
 
 if [[ "$DFX_NETWORK" == "local" ]]; then
-	echo NOT APPLICABLE
-	exit 1
+  echo NOT APPLICABLE
+  exit 1
 else
-	# Run remotely with one of the predefined configurations.
-	# Note: This is still relatively slow and error prone.  Points of friction need to be ironed
-	# out before we can resonably ask people to do this.
-	IC_REPO_DIR="${IC_REPO_DIR:-$HOME/dfn/ic-github/}"
-	ND_REPO_DIR="${ND_REPO_DIR:-$HOME/dfn/nns-dapp/}"
-	TESTNET="$DFX_NETWORK"
-	test -d "$ND_REPO_DIR" || {
-		echo "Invalid directory for nns-dapp source code: $ND_REPO_DIR"
-		exit 1
-	} >&2
-	(
-		set -euxo pipefail
-		echo "Deploying testnet..."
-		cd "$IC_REPO_DIR"
-		git checkout "$IC_COMMIT"
-		cat <<-EOF >test-accounts.json
+  # Run remotely with one of the predefined configurations.
+  # Note: This is still relatively slow and error prone.  Points of friction need to be ironed
+  # out before we can resonably ask people to do this.
+  IC_REPO_DIR="${IC_REPO_DIR:-$HOME/dfn/ic-github/}"
+  ND_REPO_DIR="${ND_REPO_DIR:-$HOME/dfn/nns-dapp/}"
+  TESTNET="$DFX_NETWORK"
+  test -d "$ND_REPO_DIR" || {
+    echo "Invalid directory for nns-dapp source code: $ND_REPO_DIR"
+    exit 1
+  } >&2
+  (
+    set -euxo pipefail
+    echo "Deploying testnet..."
+    cd "$IC_REPO_DIR"
+    git checkout "$IC_COMMIT"
+    cat <<-EOF >test-accounts.json
 			{
 			  "init_ledger_accounts":["5b315d2f6702cb3a27d826161797d7b2c2e131cd312aece51d4d5574d1247087", "2b8fbde99de881f695f279d2a892b1137bfe81a42d7694e064b1be58701e1138"]
 			}
 		EOF
 
-		./testnet/tools/icos_deploy.sh --git-revision "$IC_COMMIT" "$TESTNET" --ansible-args "-e @$PWD/test-accounts.json" || {
-			echo "Tesnet returned an error code but it returns errors for very minor reasons.  The deployment is probably fine."
-		}
-		(cd "testnet/env/$TESTNET/" && ./hosts --nns-nodes | awk '{printf "%s http://[%s]:8080\n", $1, $2}')
-		dfx-network-delete --network "$DFX_NETWORK"
-	)
+    ./testnet/tools/icos_deploy.sh --git-revision "$IC_COMMIT" "$TESTNET" --ansible-args "-e @$PWD/test-accounts.json" || {
+      echo "Tesnet returned an error code but it returns errors for very minor reasons.  The deployment is probably fine."
+    }
+    (cd "testnet/env/$TESTNET/" && ./hosts --nns-nodes | awk '{printf "%s http://[%s]:8080\n", $1, $2}')
+    dfx-network-delete --network "$DFX_NETWORK"
+  )
 fi
