Check whether creating an anchor has succeeded

diff --git a/bin/dfx-ii-create-dummy-anchor b/bin/dfx-ii-create-dummy-anchor
--- a/bin/dfx-ii-create-dummy-anchor
+++ b/bin/dfx-ii-create-dummy-anchor
@@ -36,7 +36,19 @@ CHALLENGE_KEY="$(dfx canister call internet_identity create_challenge --network 
 PUB_KEY_BLOB=$(hexdump -ve '1/1 "%.2x"' "$IDENTITY_PUB_KEY_FILE" | sed 's/../\\&/g')
 
 echo "Creating anchor."
-ANCHOR="$(dfx canister call internet_identity register "(record{pubkey=blob \"${PUB_KEY_BLOB}\";alias=\"dfx test key\";purpose=variant{authentication};key_type=variant{unknown};protection=variant{unprotected};},record{key=\"${CHALLENGE_KEY}\";chars=\"a\"},null)" --network "$DFX_NETWORK" | idl2json | jq -r .registered.user_number)"
+ANCHOR_CREATION_RESPONSE="$(dfx canister call internet_identity register "(record{pubkey=blob \"${PUB_KEY_BLOB}\";alias=\"dfx test key\";purpose=variant{authentication};key_type=variant{unknown};protection=variant{unprotected};},record{key=\"${CHALLENGE_KEY}\";chars=\"a\"},null)" --network "$DFX_NETWORK")"
+ANCHOR="$(echo "$ANCHOR_CREATION_RESPONSE" | idl2json | jq -r .registered.user_number)"
+
+# Verify that the anchor is a number:
+is_int() {
+  test "${1:-}" -eq "${1:-}" 2>/dev/null
+}
+is_int "$ANCHOR" || {
+  echo "ERROR: Failed to register a new user."
+  echo "Response:"
+  echo "$ANCHOR_CREATION_RESPONSE"
+  exit 1
+} >&2
 
 # This matches the dummy key pair generated by Internet Identity here:
 # https://github.com/dfinity/internet-identity/blob/1ce860dd0601312f6521d433c4e273215a1abc5d/src/frontend/src/utils/iiConnection.ts#L57
