Add a path in the cache in the default snapshot search path

diff --git a/bin/dfx-snapshot-restore b/bin/dfx-snapshot-restore
--- a/bin/dfx-snapshot-restore
+++ b/bin/dfx-snapshot-restore
@@ -17,11 +17,22 @@ help_text() {
 # Source the clap.bash file ---------------------------------------------------
 source "$SOURCE_DIR/clap.bash"
 # Define options
-clap.define short=s long=snapshot desc="The file to save to" variable=DFX_SNAPSHOT_FILE default="state.tar.xz"
+clap.define short=s long=snapshot desc="The file to restore.  If several paths are given, colon delimited, the first file that exists will be used." variable=DFX_SNAPSHOT_FILE default="state.tar.xz:$(dfx cache show)/snapshots/state.tar.xz"
 # Source the output file ----------------------------------------------------------
 source "$(clap.build)"
 
-DFX_SNAPSHOT_FILE="$(realpath "$DFX_SNAPSHOT_FILE")"
+readarray -td: DFX_SNAPSHOT_FILE_CANDIDATES < <(echo $DFX_SNAPSHOT_FILE)
+for CANDIDATE in "${DFX_SNAPSHOT_FILE_CANDIDATES[@]}" ; do
+	if test -e "$CANDIDATE"
+	then DFX_SNAPSHOT_FILE="$(realpath "$CANDIDATE")"
+		break
+	fi
+done
+test -e "$DFX_SNAPSHOT_FILE" || {
+	echo "ERROR: No snapshot found in: ${DFX_SNAPSHOT_FILE:-}"
+	exit 1
+}
+
 
 pushd "$HOME"
 rm -fr .local/share/dfx
