fmt

diff --git a/bin/dfx-snapshot-restore b/bin/dfx-snapshot-restore
--- a/bin/dfx-snapshot-restore
+++ b/bin/dfx-snapshot-restore
@@ -21,18 +21,17 @@ clap.define short=s long=snapshot desc="The file to restore.  If several paths a
 # Source the output file ----------------------------------------------------------
 source "$(clap.build)"
 
-readarray -td: DFX_SNAPSHOT_FILE_CANDIDATES < <(echo $DFX_SNAPSHOT_FILE)
-for CANDIDATE in "${DFX_SNAPSHOT_FILE_CANDIDATES[@]}" ; do
-	if test -e "$CANDIDATE"
-	then DFX_SNAPSHOT_FILE="$(realpath "$CANDIDATE")"
-		break
-	fi
+readarray -td: DFX_SNAPSHOT_FILE_CANDIDATES < <(echo "$DFX_SNAPSHOT_FILE")
+for CANDIDATE in "${DFX_SNAPSHOT_FILE_CANDIDATES[@]}"; do
+  if test -e "$CANDIDATE"; then
+    DFX_SNAPSHOT_FILE="$(realpath "$CANDIDATE")"
+    break
+  fi
 done
 test -e "$DFX_SNAPSHOT_FILE" || {
-	echo "ERROR: No snapshot found in: ${DFX_SNAPSHOT_FILE:-}"
-	exit 1
+  echo "ERROR: No snapshot found in: ${DFX_SNAPSHOT_FILE:-}"
+  exit 1
 }
-
 
 pushd "$HOME"
 rm -fr .local/share/dfx
