Bump IC commit & handle nulls in dfx-sns-sale-buy

diff --git a/bin/dfx-sns-sale-buy b/bin/dfx-sns-sale-buy
--- a/bin/dfx-sns-sale-buy
+++ b/bin/dfx-sns-sale-buy
@@ -17,7 +17,11 @@ export DFX_NETWORK
 
 # Set the purchased amout to the maximum allowed, if requested.
 if [[ "${AMOUNT:-}" = "max" ]]; then
-  AMOUNT_E8S="$(dfx canister call sns_swap get_state '(record {})' --network "$DFX_NETWORK" | awk '/max_participant_icp_e8s/{gsub(/_/,""); print $3}')"
+  AMOUNT_E8S="$(dfx canister call sns_swap get_state '(record {})' --network "$DFX_NETWORK" | awk '/max_participant_icp_e8s/{gsub(/_/,""); if ($3 + 0 == $3) {print $3; exit 0}}')"
+  test -n "${AMOUNT_E8S:-}" || {
+     echo "ERROR: No max_participant_icp_e8s found for SNS but purchasing the max was requested."
+     exit 1
+  }
 else
   AMOUNT_E8S="$((AMOUNT * 100000000))"
 fi
