Handle 503 errors when creating a neuron

diff --git a/bin/dfx-neuron-create b/bin/dfx-neuron-create
--- a/bin/dfx-neuron-create
+++ b/bin/dfx-neuron-create
@@ -16,11 +16,11 @@ test -z "${DFX_VERBOSE:-}" || set -x
 retry() {
   (
     set -eu
-    for ((i = 0; i < DFX_RETRIES; i++)); do
+    for ((i = 0; i < ${DFX_RETRIES:-20}; i++)); do
       if "${@}"; then
-        break
+        return
       else
-        sleep 1
+        sleep ${DFX_RETRY_SLEEP:-4}
       fi
     done
     {
@@ -31,53 +31,56 @@ retry() {
 }
 
 mk_neuron() {
-  # Create a neuron
-  PEM="$HOME/.config/dfx/identity/$DFX_IDENTITY/identity.pem"
-  test -e "$PEM" || {
-    echo "ERROR: Pem file for user '$DFX_IDENTITY' does not exist at '$PEM'"
-    exit 1
-  } >&2
-  NEURONS_DIR="$HOME/.config/dfx/identity/$DFX_IDENTITY/neurons"
-  mkdir -p "$NEURONS_DIR"
-  NEURONS_FILE="$NEURONS_DIR/$DFX_NETWORK"
-  IC_URL="$("$SOURCE_DIR/dfx-network-url" --network "$DFX_NETWORK")"
-  export IC_URL
-  # Note: Quill send puts a pile of junk on stdout and has no option to put just the response(s) somewhere safe such as a file.
+  (
+    set -euo pipefail
+    # Create a neuron
+    PEM="$HOME/.config/dfx/identity/$DFX_IDENTITY/identity.pem"
+    test -e "$PEM" || {
+      echo "ERROR: Pem file for user '$DFX_IDENTITY' does not exist at '$PEM'"
+      exit 1
+    } >&2
+    NEURONS_DIR="$HOME/.config/dfx/identity/$DFX_IDENTITY/neurons"
+    mkdir -p "$NEURONS_DIR"
+    NEURONS_FILE="$NEURONS_DIR/$DFX_NETWORK"
+    IC_URL="$("$SOURCE_DIR/dfx-network-url" --network "$DFX_NETWORK")"
+    export IC_URL
+    # Note: Quill send puts a pile of junk on stdout and has no option to put just the response(s) somewhere safe such as a file.
 
-  command=(quill neuron-stake --insecure-local-dev-mode --pem-file "$PEM" --amount "$ICP" --name 1)
-  MESSAGE="$("${command[@]}")"
-  test -n "${MESSAGE:-}" || {
-    echo "ERROR: Created an empty message."
-    command -v quill
-    echo "${command[*]}"
-    exit 1
-  } >&2
-  command=(quill send --yes --insecure-local-dev-mode -)
-  RESPONSE="$(echo "$MESSAGE" | "${command[@]}")"
-  test -n "${RESPONSE:-}" || {
-    echo "ERROR: Received an empty response."
-    echo message:
-    echo "$MESSAGE"
+    command=(quill neuron-stake --insecure-local-dev-mode --pem-file "$PEM" --amount "$ICP" --name 1)
+    MESSAGE="$("${command[@]}")"
+    test -n "${MESSAGE:-}" || {
+      echo "ERROR: Created an empty message."
+      command -v quill
+      echo "${command[*]}"
+      exit 1
+    } >&2
+    command=(quill send --yes --insecure-local-dev-mode -)
+    RESPONSE="$(echo "$MESSAGE" | "${command[@]}")"
+    test -n "${RESPONSE:-}" || {
+      echo "ERROR: Received an empty response."
+      echo message:
+      echo "$MESSAGE"
+      echo
+      echo command -v quill
+      echo "${command[*]}"
+      exit 1
+    } >&2
+    NEURON_TEXT="$(echo "$RESPONSE" | perl -e 'while($_ = <>){if (s/NeuronId = record \{ id = ([0-9_]+) : nat64 \}/\1/){ print $_ }}')"
+    test -n "${NEURON_TEXT:-}" || {
+      echo "ERROR: Could not find neuron in response:"
+      echo "$RESPONSE"
+      exit 1
+    } >&2
+    NEURON_ID="$(echo "$NEURON_TEXT" | tr -cd '[:alnum:]')"
+    test -n "${NEURON_ID:-}" || {
+      echo "Failed to get neuron ID from line: $NEURON_TEXT"
+      exit 1
+    } >&2
+
+    echo "$NEURON_ID" >>"$NEURONS_FILE"
     echo
-    echo command -v quill
-    echo "${command[*]}"
-    exit 1
-  } >&2
-  NEURON_TEXT="$(echo "$RESPONSE" | perl -e 'while($_ = <>){if (s/NeuronId = record \{ id = ([0-9_]+) : nat64 \}/\1/){ print $_ }}')"
-  test -n "${NEURON_TEXT:-}" || {
-    echo "ERROR: Could not find neuron in response:"
-    echo "$RESPONSE"
-    exit 1
-  } >&2
-  NEURON_ID="$(echo "$NEURON_TEXT" | tr -cd '[:alnum:]')"
-  test -n "${NEURON_ID:-}" || {
-    echo "Failed to get neuron ID from line: $NEURON_TEXT"
-    exit 1
-  } >&2
-
-  echo "$NEURON_ID" >>"$NEURONS_FILE"
-  echo
-  tail -n1 "$NEURONS_FILE"
+    tail -n1 "$NEURONS_FILE"
+  )
 }
 
-DFX_RETRIES=5 retry mk_neuron
+retry mk_neuron
