++

diff --git a/bin/dfx-ckbtc-import b/bin/dfx-ckbtc-import
--- a/bin/dfx-ckbtc-import
+++ b/bin/dfx-ckbtc-import
@@ -16,12 +16,13 @@ print_help() {
 source "$SOURCE_DIR/clap.bash"
 # Define options
 clap.define short=c long=commit desc="Commit of the IC repo to download canisters from" variable=IC_COMMIT default="3b1e62d3dcfa0e2e7364e4578482e0d15fb0201b"
+clap.define short=p long=prefix desc="Prefix for the local canister names" variable=LOCAL_PREFIX default="ckbtc_"
 # Source the output file ----------------------------------------------------------
 source "$(clap.build)"
 
+# These match `dfx nns import`:
 WASM_DIR="wasms"
 CANDID_DIR="candid"
-LOCAL_PREFIX="ckbtc_"
 
 test -e dfx.json || {
   echo "ERROR: No dfx.json found.  Please run this from inside a dfx project."
@@ -70,3 +71,36 @@ popd
 
 : Update dfx.json
 jq -s '.[0] * .[1]' dfx.json "${SOURCE_DIR}/dfx-ckbtc-dfx.json" | sponge dfx.json
+
+: Verify that all filea re present and correct
+for canister in minter ledger index ; do
+	canister_config="$(n="$LOCAL_PREFIX$canister" jq '.canisters[env.n]' dfx.json)"
+	[[ "$canister_config" != "null" ]] || {
+	    printf "ERROR: %s\n" "$LOCAL_PREFIX$canister should be in dfx.json"
+	    exit 1
+	} 2>&1
+        canister_wasm_path="$(printf "%s" "$canister_config" | jq .wasm)"
+	[[ "$canister_wasm_path" != "null" ]] || {
+	    printf "ERROR: %s\n" "$LOCAL_PREFIX$canister config in dfx.json should include \"wasm\": <PATH TO WASM>"
+	    exit 1
+	} >&2
+        test -e "$canister_wasm_path" || {
+	    printf "ERROR: %s\n" "Wasm for $LOCAL_PREFIX$canister for found at the path given in dfx.json: '$canister_wasm_path'"
+	    exit 1
+	} >&2
+        canister_did_path="$(printf "%s" "$canister_config" | jq .candid)"
+	[[ "$canister_did_path" != "null" ]] || {
+	    printf "ERROR: %s\n" "$LOCAL_PREFIX$canister config in dfx.json should include \"candid\": <PATH TO .did FILE>"
+	    exit 1
+	} >&2
+        test -e "$canister_did_path" || {
+	    printf "ERROR: %s\n" "Candid for $LOCAL_PREFIX$canister for found at the path given in dfx.json: '$canister_did_path'"
+	    exit 1
+	} >&2
+        if command -v idl2json
+	then idl2json < "$canister_did_path" >/dev/null || {
+	    printf "ERROR: %s\n" "Candid for $LOCAL_PREFIX$canister at '$canister_did_path' is not a valid did file."
+	    exit 1
+	} >&2
+	fi
+done
