shfmt

diff --git a/bin/dfx-canister-import b/bin/dfx-canister-import
--- a/bin/dfx-canister-import
+++ b/bin/dfx-canister-import
@@ -3,34 +3,34 @@ set -euo pipefail
 cd "$(dirname "$(realpath "$0")")/.."
 
 help_text() {
-  cat <<-EOF
+	cat <<-EOF
 
-	Imports candid files from a remote project.
+		Imports candid files from a remote project.
 
-	Polyfill for: "dfx canister import"
+		Polyfill for: "dfx canister import"
 
-	Usage: dfx canister import [--prefix <CANISTER_NAME_PREFIX>] <URL|PATH_TO_REMOTE_DFX> <CANISTER_NAME>
+		Usage: dfx canister import [--prefix <CANISTER_NAME_PREFIX>] <URL|PATH_TO_REMOTE_DFX> <CANISTER_NAME>
 
-	Arguments:
-	<URL|PATH_TO_REMOTE_DFX>
-	  The location of a remote dfx.json file.
-	  Example: To import the NNS canisters, use: https://raw.githubusercontent.com/dfinity/ic/master/rs/nns/dfx.json
+		Arguments:
+		<URL|PATH_TO_REMOTE_DFX>
+		  The location of a remote dfx.json file.
+		  Example: To import the NNS canisters, use: https://raw.githubusercontent.com/dfinity/ic/master/rs/nns/dfx.json
 
-	<CANISTER_NAME>
-	  The name of the canister to import.  If "--all" is given, all canisters will be imported.
+		<CANISTER_NAME>
+		  The name of the canister to import.  If "--all" is given, all canisters will be imported.
 
-	Flags:
-	--help
-	  Prints this help text and exits.
+		Flags:
+		--help
+		  Prints this help text and exits.
 
-	--prefix <CANISTER_NAME_PREFIX>
-	  A prefix to add to imported canister names.
+		--prefix <CANISTER_NAME_PREFIX>
+		  A prefix to add to imported canister names.
 
-	--ids
-	  Import the canister_ids.json (in its entirety or the specified canisters only).
+		--ids
+		  Import the canister_ids.json (in its entirety or the specified canisters only).
 
-	  Example: If the prefix is "foo-" and a remote canister is called "bar"
-		   then the canister will be called "foo-bar" in the local dfx.json.
+		  Example: If the prefix is "foo-" and a remote canister is called "bar"
+			   then the canister will be called "foo-bar" in the local dfx.json.
 
 	EOF
 }
@@ -38,96 +38,96 @@ help_text() {
 unset CANISTER_NAME_PREFIX
 ACTION=IMPORT_DFX
 while (($# > 0)); do
-  arg="$1"
-  shift 1
-  case "$arg" in
-  --help)
-    help_text
-    exit 0
-    ;;
-  --prefix)
-    CANISTER_NAME_PREFIX="${1}"
-    shift 1
-    ;;
-  --ids)
-    ACTION="IMPORT_CANISTER_IDS"
-    ;;
-  *)
-    REMOTE_DFX="${arg}"
-    CANISTER_NAME="${1:---all}"
-    shift 1 || true
-    ;;
-  esac
+	arg="$1"
+	shift 1
+	case "$arg" in
+	--help)
+		help_text
+		exit 0
+		;;
+	--prefix)
+		CANISTER_NAME_PREFIX="${1}"
+		shift 1
+		;;
+	--ids)
+		ACTION="IMPORT_CANISTER_IDS"
+		;;
+	*)
+		REMOTE_DFX="${arg}"
+		CANISTER_NAME="${1:---all}"
+		shift 1 || true
+		;;
+	esac
 done
 
 copy_from_anywhere() {
-  if test -f "$1" || test -L "$1"; then
-    cat "$1" >"$2"
-  else
-    curl -SL "$1" >"$2"
-  fi
+	if test -f "$1" || test -L "$1"; then
+		cat "$1" >"$2"
+	else
+		curl -SL "$1" >"$2"
+	fi
 }
 import_canister_dfx() {
-  (
-    set -euxo pipefail
-    export canister_name="$1"
-    export local_canister_name="${CANISTER_NAME_PREFIX:-}${canister_name}"
-    export source_did_path="$REMOTE_DFX_DIR/$(jq -r '.canisters[env.canister_name].candid' "$COPY_OF_REMOTE_DFX")"
-    export source_did_path="$(echo "$source_did_path" | sed -E 's_([^:])/+_\1/_g;:a;s_[^/]*\/\.\.\/__g;ta')"
-    export target_did_path="$LOCAL_CANDID_DIR/${local_canister_name}.did"
-    mkdir -p "$LOCAL_CANDID_DIR"
-    copy_from_anywhere "$source_did_path" "$target_did_path"
-    cat <<<"$(jq '.canisters[env.local_canister_name] = {candid: (env.target_did_path), build: "", wasm: "", type: "custom"}' "$COPY_OF_LOCAL_DFX")" >"$COPY_OF_LOCAL_DFX"
-  )
+	(
+		set -euxo pipefail
+		export canister_name="$1"
+		export local_canister_name="${CANISTER_NAME_PREFIX:-}${canister_name}"
+		export source_did_path="$REMOTE_DFX_DIR/$(jq -r '.canisters[env.canister_name].candid' "$COPY_OF_REMOTE_DFX")"
+		export source_did_path="$(echo "$source_did_path" | sed -E 's_([^:])/+_\1/_g;:a;s_[^/]*\/\.\.\/__g;ta')"
+		export target_did_path="$LOCAL_CANDID_DIR/${local_canister_name}.did"
+		mkdir -p "$LOCAL_CANDID_DIR"
+		copy_from_anywhere "$source_did_path" "$target_did_path"
+		cat <<<"$(jq '.canisters[env.local_canister_name] = {candid: (env.target_did_path), build: "", wasm: "", type: "custom"}' "$COPY_OF_LOCAL_DFX")" >"$COPY_OF_LOCAL_DFX"
+	)
 }
 import_dfx_main() {
-  REMOTE_DFX_DIR="$(dirname "${REMOTE_DFX}X")" # Maps: foo/dfx.json -> foo ; foo/ -> foo
-  REMOTE_DFX="${REMOTE_DFX_DIR:-.}/dfx.json"
-  COPY_OF_REMOTE_DFX="$(mktemp)"
-  COPY_OF_LOCAL_DFX="$(mktemp)"
-  LOCAL_CANDID_DIR="candid"
+	REMOTE_DFX_DIR="$(dirname "${REMOTE_DFX}X")" # Maps: foo/dfx.json -> foo ; foo/ -> foo
+	REMOTE_DFX="${REMOTE_DFX_DIR:-.}/dfx.json"
+	COPY_OF_REMOTE_DFX="$(mktemp)"
+	COPY_OF_LOCAL_DFX="$(mktemp)"
+	LOCAL_CANDID_DIR="candid"
 
-  cp dfx.json "$COPY_OF_LOCAL_DFX"
-  copy_from_anywhere "$REMOTE_DFX" "$COPY_OF_REMOTE_DFX"
-  if [[ "$CANISTER_NAME" == "--all" ]]; then
-    for canister_name in $(jq -r '.canisters | keys | .[]' "$COPY_OF_REMOTE_DFX"); do
-      import_canister_dfx "$canister_name"
-    done
-  else
-    import_canister_dfx "$CANISTER_NAME"
-  fi
-  cp "$COPY_OF_LOCAL_DFX" dfx.json
-  rm "$COPY_OF_REMOTE_DFX"
-  echo OK
+	cp dfx.json "$COPY_OF_LOCAL_DFX"
+	copy_from_anywhere "$REMOTE_DFX" "$COPY_OF_REMOTE_DFX"
+	if [[ "$CANISTER_NAME" == "--all" ]]; then
+		for canister_name in $(jq -r '.canisters | keys | .[]' "$COPY_OF_REMOTE_DFX"); do
+			import_canister_dfx "$canister_name"
+		done
+	else
+		import_canister_dfx "$CANISTER_NAME"
+	fi
+	cp "$COPY_OF_LOCAL_DFX" dfx.json
+	rm "$COPY_OF_REMOTE_DFX"
+	echo OK
 }
 import_canister_ids_main() {
-  REMOTE_DFX_DIR="$(dirname "${REMOTE_DFX}X")" # Maps: foo/dfx.json -> foo ; foo/ -> foo
-  REMOTE_CANISTER_IDS_PATH="${REMOTE_DFX_DIR:-.}/canister_ids.json"
-  COPY_OF_REMOTE_CANISTER_IDS="$(mktemp)"
-  COPY_OF_LOCAL_CANISTER_IDS="$(mktemp)"
-  touch canister_ids.json
-  cp canister_ids.json "$COPY_OF_LOCAL_CANISTER_IDS"
-  copy_from_anywhere "$REMOTE_CANISTER_IDS_PATH" "$COPY_OF_REMOTE_CANISTER_IDS"
-  if [[ "$CANISTER_NAME" == "--all" ]]; then
-    cat <<<"$(jq -s '.[0] * .[1]' "$COPY_OF_LOCAL_CANISTER_IDS" "$COPY_OF_REMOTE_CANISTER_IDS")" >"$COPY_OF_LOCAL_CANISTER_IDS"
-  else
-    export CANISTER_NAME
-    cat <<<"$(jq -s '.[0] * {(env.CANISTER_NAME): .[1](env.CANISTER_NAME)}' "$COPY_OF_LOCAL_CANISTER_IDS" "$COPY_OF_REMOTE_CANISTER_IDS")" >"$COPY_OF_LOCAL_CANISTER_IDS"
-  fi
-  mv "$COPY_OF_LOCAL_CANISTER_IDS" canister_ids.json
-  rm "$COPY_OF_REMOTE_CANISTER_IDS"
-  echo OK
+	REMOTE_DFX_DIR="$(dirname "${REMOTE_DFX}X")" # Maps: foo/dfx.json -> foo ; foo/ -> foo
+	REMOTE_CANISTER_IDS_PATH="${REMOTE_DFX_DIR:-.}/canister_ids.json"
+	COPY_OF_REMOTE_CANISTER_IDS="$(mktemp)"
+	COPY_OF_LOCAL_CANISTER_IDS="$(mktemp)"
+	touch canister_ids.json
+	cp canister_ids.json "$COPY_OF_LOCAL_CANISTER_IDS"
+	copy_from_anywhere "$REMOTE_CANISTER_IDS_PATH" "$COPY_OF_REMOTE_CANISTER_IDS"
+	if [[ "$CANISTER_NAME" == "--all" ]]; then
+		cat <<<"$(jq -s '.[0] * .[1]' "$COPY_OF_LOCAL_CANISTER_IDS" "$COPY_OF_REMOTE_CANISTER_IDS")" >"$COPY_OF_LOCAL_CANISTER_IDS"
+	else
+		export CANISTER_NAME
+		cat <<<"$(jq -s '.[0] * {(env.CANISTER_NAME): .[1](env.CANISTER_NAME)}' "$COPY_OF_LOCAL_CANISTER_IDS" "$COPY_OF_REMOTE_CANISTER_IDS")" >"$COPY_OF_LOCAL_CANISTER_IDS"
+	fi
+	mv "$COPY_OF_LOCAL_CANISTER_IDS" canister_ids.json
+	rm "$COPY_OF_REMOTE_CANISTER_IDS"
+	echo OK
 }
 
 case "${ACTION}" in
 IMPORT_DFX)
-  import_dfx_main
-  ;;
+	import_dfx_main
+	;;
 IMPORT_CANISTER_IDS)
-  import_canister_ids_main
-  ;;
+	import_canister_ids_main
+	;;
 *)
-  echo "Internal error: Unknown action '${ACTION}'" >&2
-  exit 1
-  ;;
+	echo "Internal error: Unknown action '${ACTION}'" >&2
+	exit 1
+	;;
 esac
diff --git a/bin/dfx-nns-wasm-download b/bin/dfx-nns-wasm-download
--- a/bin/dfx-nns-wasm-download
+++ b/bin/dfx-nns-wasm-download
@@ -8,122 +8,125 @@ set -x
 SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
 DOWNLOAD_DIR="$PWD/wasms"
 NO_CLOBBER=""
-IC_COMMIT="$(. "$SOURCE_DIR/versions.bash" ; echo "$IC_COMMIT")"
+IC_COMMIT="$(
+	. "$SOURCE_DIR/versions.bash"
+	echo "$IC_COMMIT"
+)"
 
 help_text() {
-  cat <<-EOF
-	Downloads prebuilt internet computer artifacts:
-	- NNS wasm canisters
-	- NNS wasm canister installer
+	cat <<-EOF
+		Downloads prebuilt internet computer artifacts:
+		- NNS wasm canisters
+		- NNS wasm canister installer
 
-	Flags:
-	--help
-	  Prints this help text
+		Flags:
+		--help
+		  Prints this help text
 
-	--download-dir <DIR>
-	  Specifies where the artifacts should be downloaded.
-	  Default: '$DOWNLOAD_DIR'
-	  The download dir is printed on stdout for use by other programs.
+		--download-dir <DIR>
+		  Specifies where the artifacts should be downloaded.
+		  Default: '$DOWNLOAD_DIR'
+		  The download dir is printed on stdout for use by other programs.
 
-	--commit <IC_COMMIT>
-	  Commit in the IC repo.
-	  Note: Not all commits are available as artifacts to download.
+		--commit <IC_COMMIT>
+		  Commit in the IC repo.
+		  Note: Not all commits are available as artifacts to download.
 
-	--no-clobber
-	  Don't replace existing files.
-	
+		--no-clobber
+		  Don't replace existing files.
+
 	EOF
 }
 
 while (($# > 0)); do
-  arg="$1"
-  shift 1
-  case "$arg" in
-  --help)
-    help_text
-    exit 0
-    ;;
-  --download-dir)
-    DOWNLOAD_DIR="$(realpath "$1")"
-    test -d "$DOWNLOAD_DIR" || {
-      printf "ERROR: %s '%s'\n" "Download dir does not exist:" "$1"
-      exit 1
-    } >&2
-    shift 1
-    ;;
-  --ic-commit)
-    IC_COMMIT="$1"
-    shift 1
-    ;;
-  --no-clobber)
-    NO_CLOBBER=nc
-    ;;
-  *)
-    {
-      printf "ERROR: %s '%s'\n" "Unknown argument:" "$arg"
-      printf "Usage:"
-      help_text
-    } >&2
-    exit 1
-    ;;
-  esac
+	arg="$1"
+	shift 1
+	case "$arg" in
+	--help)
+		help_text
+		exit 0
+		;;
+	--download-dir)
+		DOWNLOAD_DIR="$(realpath "$1")"
+		test -d "$DOWNLOAD_DIR" || {
+			printf "ERROR: %s '%s'\n" "Download dir does not exist:" "$1"
+			exit 1
+		} >&2
+		shift 1
+		;;
+	--ic-commit)
+		IC_COMMIT="$1"
+		shift 1
+		;;
+	--no-clobber)
+		NO_CLOBBER=nc
+		;;
+	*)
+		{
+			printf "ERROR: %s '%s'\n" "Unknown argument:" "$arg"
+			printf "Usage:"
+			help_text
+		} >&2
+		exit 1
+		;;
+	esac
 done
 
 mkdir -p "$DOWNLOAD_DIR"
 echo "$DOWNLOAD_DIR"
 
 get_binary() {
-  local FILENAME
-  FILENAME="$1"
-  if test -e "$DOWNLOAD_DIR/$FILENAME" && test -n "${NO_CLOBBER:-}"; then
-    return
-  fi
-  local TMP_FILE
-  TMP_FILE="$(mktemp)"
-  local OS
-  OS="$(uname)"
-  case "$OS" in
-  Darwin)
-    curl "https://download.dfinity.systems/ic/${IC_COMMIT}/nix-release/x86_64-darwin/${FILENAME}.gz" | gunzip >"$TMP_FILE"
-    ;;
-  Linux)
-    curl "https://download.dfinity.systems/ic/${IC_COMMIT}/release/${FILENAME}.gz" | gunzip >"$TMP_FILE"
-    ;;
-  *)
-    printf "ERROR: %s '%s'\n" \
-      "Cannot download binary" "$FILENAME" \
-      "Unsupported platform:" "$OS" \
-      >&2
-    exit 1
-    ;;
-  esac
-  install -m 755 "$TMP_FILE" "$DOWNLOAD_DIR/$FILENAME"
-  rm "$TMP_FILE"
+	local FILENAME
+	FILENAME="$1"
+	if test -e "$DOWNLOAD_DIR/$FILENAME" && test -n "${NO_CLOBBER:-}"; then
+		return
+	fi
+	local TMP_FILE
+	TMP_FILE="$(mktemp)"
+	local OS
+	OS="$(uname)"
+	case "$OS" in
+	Darwin)
+		curl "https://download.dfinity.systems/ic/${IC_COMMIT}/nix-release/x86_64-darwin/${FILENAME}.gz" | gunzip >"$TMP_FILE"
+		;;
+	Linux)
+		curl "https://download.dfinity.systems/ic/${IC_COMMIT}/release/${FILENAME}.gz" | gunzip >"$TMP_FILE"
+		;;
+	*)
+		printf "ERROR: %s '%s'\n" \
+			"Cannot download binary" "$FILENAME" \
+			"Unsupported platform:" "$OS" \
+			>&2
+		exit 1
+		;;
+	esac
+	install -m 755 "$TMP_FILE" "$DOWNLOAD_DIR/$FILENAME"
+	rm "$TMP_FILE"
 }
 
 # Downloads wasm files.
 get_wasm() {
-  local FILENAME
-  FILENAME="$1"
-  shift 1
-  if test -e "$DOWNLOAD_DIR/$FILENAME" && test -n "${NO_CLOBBER:-}"; then
-    echo "Already downloaded $FILENAME"
-  else
-    local TMP_FILE
-    TMP_FILE="$(mktemp)"
-    curl "https://download.dfinity.systems/ic/${IC_COMMIT}/canisters/${FILENAME}.gz" | gunzip >"$TMP_FILE"
-    install -m 644 "$TMP_FILE" "$DOWNLOAD_DIR/$FILENAME"
-    rm "$TMP_FILE"
-  fi
-  (
-    cd "$DOWNLOAD_DIR"
-    while (($# > 0)); do
-      LINK_NAME="$1"
-      shift 1
-      rm -f "$LINK_NAME"
-      ln -s "$FILENAME" "$LINK_NAME"
-    done
-  )
+	local FILENAME
+	FILENAME="$1"
+	shift 1
+	if test -e "$DOWNLOAD_DIR/$FILENAME" && test -n "${NO_CLOBBER:-}"; then
+		echo "Already downloaded $FILENAME"
+	else
+		local TMP_FILE
+		TMP_FILE="$(mktemp)"
+		curl "https://download.dfinity.systems/ic/${IC_COMMIT}/canisters/${FILENAME}.gz" | gunzip >"$TMP_FILE"
+		install -m 644 "$TMP_FILE" "$DOWNLOAD_DIR/$FILENAME"
+		rm "$TMP_FILE"
+	fi
+	(
+		cd "$DOWNLOAD_DIR"
+		while (($# > 0)); do
+			LINK_NAME="$1"
+			shift 1
+			rm -f "$LINK_NAME"
+			ln -s "$FILENAME" "$LINK_NAME"
+		done
+	)
 }
 
 get_binary ic-nns-init
diff --git a/bin/dfx-sns-swap-start b/bin/dfx-sns-swap-start
--- a/bin/dfx-sns-swap-start
+++ b/bin/dfx-sns-swap-start
@@ -5,94 +5,94 @@ SWAP_CANISTER_NAME="sns_swap"
 DFX_NETWORK="${DFX_NETWORK:-local}"
 
 help_text() {
-  cat <<-EOF
-	Starts an SNS swap.
+	cat <<-EOF
+		Starts an SNS swap.
 
-	Flags:
-	--dfx-network <DFX_NETWORK>
-	  The network in dfx.json with the swap canister.
-	  Default: None, this is required.
+		Flags:
+		--dfx-network <DFX_NETWORK>
+		  The network in dfx.json with the swap canister.
+		  Default: None, this is required.
 
-	--swap-canister <SWAP_CANISTER_ID>
-	  The swap canister ID.
-	  Default: The '${SWAP_CANISTER_NAME}' entry in 'canister_ids.json'
+		--swap-canister <SWAP_CANISTER_ID>
+		  The swap canister ID.
+		  Default: The '${SWAP_CANISTER_NAME}' entry in 'canister_ids.json'
 
-	--title <TITLE>
-	  The title of the proposal
-	  Default: Something meaningless
+		--title <TITLE>
+		  The title of the proposal
+		  Default: Something meaningless
 
-	--url <URL>
-	  The URL of a page describing the SNS
-	  Default: Something meaningless
+		--url <URL>
+		  The URL of a page describing the SNS
+		  Default: Something meaningless
 
-	--proposer <PROPOSER_NEURON_ID>
-	  The proposing neuron ID.
-	  Default: Interactive commands to set up a neuron and hotkey.
+		--proposer <PROPOSER_NEURON_ID>
+		  The proposing neuron ID.
+		  Default: Interactive commands to set up a neuron and hotkey.
 
-	Env vars:
-	  DFX_NETWORK
-	  SWAP_CANISTER_ID
-	  TITLE
-	  URL
-	  PROPOSER_NEURON_ID
+		Env vars:
+		  DFX_NETWORK
+		  SWAP_CANISTER_ID
+		  TITLE
+		  URL
+		  PROPOSER_NEURON_ID
 	EOF
 }
 
 dfx_network_is_valid() {
-  [[ "${DFX_NETWORK:-}" == "local" ]] || jq -e '.networks[env.DFX_NETWORK]' dfx.json >/dev/null
+	[[ "${DFX_NETWORK:-}" == "local" ]] || jq -e '.networks[env.DFX_NETWORK]' dfx.json >/dev/null
 }
 dfx_network_check_specified() {
-  test -n "${DFX_NETWORK:-}" || {
-    echo "ERROR: DFX_NETWORK not set.  Please use: --dfx-network <DFX_NETWORK>" >&2
-    exit 1
-  }
+	test -n "${DFX_NETWORK:-}" || {
+		echo "ERROR: DFX_NETWORK not set.  Please use: --dfx-network <DFX_NETWORK>" >&2
+		exit 1
+	}
 }
 dfx_network_check_valid() {
-  DFX_NETWORK="$DFX_NETWORK" dfx_network_is_valid || {
-    cat <<-EOF
+	DFX_NETWORK="$DFX_NETWORK" dfx_network_is_valid || {
+		cat <<-EOF
 
-	ERROR: No such network in dfx.json.
-	       Available networks are:
-	       $(jq -er '.networks | keys | join(" ")' dfx.json)
+			ERROR: No such network in dfx.json.
+			       Available networks are:
+			       $(jq -er '.networks | keys | join(" ")' dfx.json)
 
-	EOF
-    exit 1
-  }
+		EOF
+		exit 1
+	}
 }
 
 while (($# > 0)); do
-  arg="$1"
-  shift 1
-  case "$arg" in
-  --help)
-    help_text
-    exit 0
-    ;;
-  --dfx-network)
-    DFX_NETWORK="$1"
-    shift 1
-    dfx_network_check_valid
-    ;;
-  --proposer)
-    PROPOSER_NEURON_ID="${1:-}"
-    shift 1
-    ;;
-  --title)
-    TITLE="${1:-}"
-    shift 1
-    ;;
-  --url)
-    URL="${1:-}"
-    shift 1
-    ;;
-  *)
-    cat <<-EOF >&2
-	ERROR: Unrecognised argument: '$arg'
-	Please use --help for usage.
-	EOF
-    exit 1
-    ;;
-  esac
+	arg="$1"
+	shift 1
+	case "$arg" in
+	--help)
+		help_text
+		exit 0
+		;;
+	--dfx-network)
+		DFX_NETWORK="$1"
+		shift 1
+		dfx_network_check_valid
+		;;
+	--proposer)
+		PROPOSER_NEURON_ID="${1:-}"
+		shift 1
+		;;
+	--title)
+		TITLE="${1:-}"
+		shift 1
+		;;
+	--url)
+		URL="${1:-}"
+		shift 1
+		;;
+	*)
+		cat <<-EOF >&2
+			ERROR: Unrecognised argument: '$arg'
+			Please use --help for usage.
+		EOF
+		exit 1
+		;;
+	esac
 done
 
 dfx_network_check_specified
@@ -100,14 +100,14 @@ dfx_network_check_valid
 
 : "Tell the user how to set up a neuron, if none has been provided."
 test -n "${PROPOSER_NEURON_ID:-}" || {
-  echo
-  echo "Please create a neuron, e.g. in the nns-dapp front end."
-  read -rp "Press enter when done... " _
-  echo
-  read -rp "Please enter the ID of the neuron: " PROPOSER_NEURON_ID
-  echo
-  echo "Please add $(dfx identity --network "$DFX_NETWORK" get-principal) as a hotkey to the neuron."
-  read -rp "Press enter when done... " _
+	echo
+	echo "Please create a neuron, e.g. in the nns-dapp front end."
+	read -rp "Press enter when done... " _
+	echo
+	read -rp "Please enter the ID of the neuron: " PROPOSER_NEURON_ID
+	echo
+	echo "Please add $(dfx identity --network "$DFX_NETWORK" get-principal) as a hotkey to the neuron."
+	read -rp "Press enter when done... " _
 }
 
 test -n "${SWAP_CANISTER_ID:-}" || SWAP_CANISTER_ID="$(dfx canister --network "$DFX_NETWORK" id sns_swap)"
diff --git a/bin/test-readme b/bin/test-readme
--- a/bin/test-readme
+++ b/bin/test-readme
@@ -2,71 +2,71 @@
 set -euo pipefail
 
 print_help() {
-  cat <<-EOF
-	Tests the commands in the README.
+	cat <<-EOF
+		Tests the commands in the README.
 
-	Usage: $(basename "$0") [flags]
+		Usage: $(basename "$0") [flags]
 
-	Flags:
-	--help
-	  Prints this help text.
+		Flags:
+		--help
+		  Prints this help text.
 
-	--dry-run
-	  Prints the commands without executing them.
+		--dry-run
+		  Prints the commands without executing them.
 
-	--ssh)
-	  Clones from github via ssh instead of https.
+		--ssh)
+		  Clones from github via ssh instead of https.
 	EOF
 }
 
 AUTH=http
 modify_auth() {
-  case "${AUTH:-}" in
-  ssh) sed 's!https://github.com/!git@github.com:!g' ;;
-  *) cat ;;
-  esac
+	case "${AUTH:-}" in
+	ssh) sed 's!https://github.com/!git@github.com:!g' ;;
+	*) cat ;;
+	esac
 }
 
 COMMAND=execute_bash
 execute_bash() {
-  bash -euxo pipefail "${@}"
+	bash -euxo pipefail "${@}"
 }
 
 while (($# > 0)); do
-  arg="$1"
-  shift 1
-  case "${arg:-}" in
-  --help)
-    print_help
-    exit 0
-    ;;
-  --dry-run)
-    COMMAND="cat"
-    ;;
-  --ssh)
-    AUTH="ssh"
-    ;;
-  *)
-    {
-      echo "ERROR: Unrecognized argument: ${arg:-}"
-      exit 1
-    } >&2
-    ;;
-  esac
+	arg="$1"
+	shift 1
+	case "${arg:-}" in
+	--help)
+		print_help
+		exit 0
+		;;
+	--dry-run)
+		COMMAND="cat"
+		;;
+	--ssh)
+		AUTH="ssh"
+		;;
+	*)
+		{
+			echo "ERROR: Unrecognized argument: ${arg:-}"
+			exit 1
+		} >&2
+		;;
+	esac
 done
 
 cd "$(dirname "$(realpath "$0")")/.."
 
 if git diff | grep -q .; then
-  {
-    echo "ERROR: Refusing to test unclean repo."
-    exit 1
-  } >&2
+	{
+		echo "ERROR: Refusing to test unclean repo."
+		exit 1
+	} >&2
 fi
 # We make changes to the README.  Better undo any changes.
 function cleanup {
-  git checkout README.md
-  dfx stop
+	git checkout README.md
+	dfx stop
 }
 trap cleanup EXIT
 
