Import canister IDs

diff --git a/bin/dfx-canister-import b/bin/dfx-canister-import
--- a/bin/dfx-canister-import
+++ b/bin/dfx-canister-import
@@ -26,13 +26,17 @@ help_text() {
 	--prefix <CANISTER_NAME_PREFIX>
 	  A prefix to add to imported canister names.
 
+	--ids
+	  Import the canister_ids.json (in its entirety or the specified canisters only).
+
 	  Example: If the prefix is "foo-" and a remote canister is called "bar"
-	           then the canister will be called "foo-bar" in the local dfx.json.
+		   then the canister will be called "foo-bar" in the local dfx.json.
 
 	EOF
 }
 
 unset CANISTER_NAME_PREFIX
+ACTION=IMPORT_DFX
 while (($# > 0)); do
   arg="$1"
   shift 1
@@ -45,6 +49,9 @@ while (($# > 0)); do
     CANISTER_NAME_PREFIX="${1}"
     shift 1
     ;;
+  --ids)
+    ACTION="IMPORT_CANISTER_IDS"
+    ;;
   *)
     REMOTE_DFX="${arg}"
     CANISTER_NAME="${1:---all}"
@@ -53,11 +60,6 @@ while (($# > 0)); do
   esac
 done
 
-REMOTE_DFX_DIR="${REMOTE_DFX%dfx.json}"
-COPY_OF_REMOTE_DFX="$(mktemp)"
-COPY_OF_LOCAL_DFX="$(mktemp)"
-LOCAL_CANDID_DIR="candid"
-
 copy_from_anywhere() {
   if test -f "$1" || test -L "$1"; then
     cat "$1" >"$2"
@@ -65,7 +67,7 @@ copy_from_anywhere() {
     curl -SL "$1" >"$2"
   fi
 }
-import_canister() {
+import_canister_dfx() {
   (
     set -euxo pipefail
     export canister_name="$1"
@@ -78,17 +80,54 @@ import_canister() {
     cat <<<"$(jq '.canisters[env.local_canister_name] = {candid: (env.target_did_path), build: "", wasm: "", type: "custom"}' "$COPY_OF_LOCAL_DFX")" >"$COPY_OF_LOCAL_DFX"
   )
 }
+import_dfx_main() {
+  REMOTE_DFX_DIR="$(dirname "${REMOTE_DFX}X")" # Maps: foo/dfx.json -> foo ; foo/ -> foo
+  REMOTE_DFX="${REMOTE_DFX_DIR:-.}/dfx.json"
+  COPY_OF_REMOTE_DFX="$(mktemp)"
+  COPY_OF_LOCAL_DFX="$(mktemp)"
+  LOCAL_CANDID_DIR="candid"
 
-cp dfx.json "$COPY_OF_LOCAL_DFX"
-copy_from_anywhere "$REMOTE_DFX" "$COPY_OF_REMOTE_DFX"
-if [[ "$CANISTER_NAME" == "--all" ]]; then
-  for canister_name in $(jq -r '.canisters | keys | .[]' "$COPY_OF_REMOTE_DFX"); do
-    import_canister "$canister_name"
-  done
-else
-  import_canister "$CANISTER_NAME"
-fi
+  cp dfx.json "$COPY_OF_LOCAL_DFX"
+  copy_from_anywhere "$REMOTE_DFX" "$COPY_OF_REMOTE_DFX"
+  if [[ "$CANISTER_NAME" == "--all" ]]; then
+    for canister_name in $(jq -r '.canisters | keys | .[]' "$COPY_OF_REMOTE_DFX"); do
+      import_canister_dfx "$canister_name"
+    done
+  else
+    import_canister_dfx "$CANISTER_NAME"
+  fi
+  cp "$COPY_OF_LOCAL_DFX" dfx.json
+  rm "$COPY_OF_REMOTE_DFX"
+  echo OK
+}
+import_canister_ids_main() {
+  REMOTE_DFX_DIR="$(dirname "${REMOTE_DFX}X")" # Maps: foo/dfx.json -> foo ; foo/ -> foo
+  REMOTE_CANISTER_IDS_PATH="${REMOTE_DFX_DIR:-.}/canister_ids.json"
+  COPY_OF_REMOTE_CANISTER_IDS="$(mktemp)"
+  COPY_OF_LOCAL_CANISTER_IDS="$(mktemp)"
+  touch canister_ids.json
+  cp canister_ids.json "$COPY_OF_LOCAL_CANISTER_IDS"
+  copy_from_anywhere "$REMOTE_CANISTER_IDS_PATH" "$COPY_OF_REMOTE_CANISTER_IDS"
+  if [[ "$CANISTER_NAME" == "--all" ]]; then
+    cat <<<"$(jq -s '.[0] * .[1]' "$COPY_OF_LOCAL_CANISTER_IDS" "$COPY_OF_REMOTE_CANISTER_IDS")" >"$COPY_OF_LOCAL_CANISTER_IDS"
+  else
+    export CANISTER_NAME
+    cat <<<"$(jq -s '.[0] * {(env.CANISTER_NAME): .[1](env.CANISTER_NAME)}' "$COPY_OF_LOCAL_CANISTER_IDS" "$COPY_OF_REMOTE_CANISTER_IDS")" >"$COPY_OF_LOCAL_CANISTER_IDS"
+  fi
+  mv "$COPY_OF_LOCAL_CANISTER_IDS" canister_ids.json
+  rm "$COPY_OF_REMOTE_CANISTER_IDS"
+  echo OK
+}
 
-cp "$COPY_OF_LOCAL_DFX" dfx.json
-rm "$COPY_OF_REMOTE_DFX"
-echo OK
+case "${ACTION}" in
+IMPORT_DFX)
+  import_dfx_main
+  ;;
+IMPORT_CANISTER_IDS)
+  import_canister_ids_main
+  ;;
+*)
+  echo "Internal error: Unknown action '${ACTION}'" >&2
+  exit 1
+  ;;
+esac
