Add checks

diff --git a/bin/dfx-ii-create-dummy-anchor b/bin/dfx-ii-create-dummy-anchor
--- a/bin/dfx-ii-create-dummy-anchor
+++ b/bin/dfx-ii-create-dummy-anchor
@@ -38,6 +38,15 @@ PUB_KEY_BLOB=$(hexdump -ve '1/1 "%.2x"' "$IDENTITY_PUB_KEY_FILE" | sed 's/../\\&
 echo "Creating anchor."
 ANCHOR="$(dfx canister call internet_identity register "(record{pubkey=blob \"${PUB_KEY_BLOB}\";alias=\"dfx test key\";purpose=variant{authentication};key_type=variant{unknown};protection=variant{unprotected};},record{key=\"${CHALLENGE_KEY}\";chars=\"a\"},null)" --network "$DFX_NETWORK" | idl2json | jq -r .registered.user_number)"
 
+# Verify that the anchor is a number:
+is_int() {
+  test "${1:-}" -eq "${1:-}" 2>/dev/null
+}
+is_int "$ANCHOR" || {
+  echo "ERROR: Failed to register a new user."
+  exit 1
+} >&2
+
 # This matches the dummy key pair generated by Internet Identity here:
 # https://github.com/dfinity/internet-identity/blob/1ce860dd0601312f6521d433c4e273215a1abc5d/src/frontend/src/utils/iiConnection.ts#L57
 DUMMY_PUB_KEY_BLOB='0*0\05\06\03+ep\03!\00;j\27\bc\ce\b6\a4-b\a3\a8\d0*o\0dse2\15w\1d\e2C\a6:\c0H\a1\8bY\da)'
@@ -52,7 +61,7 @@ add_device() {
   DEVICE_KEY_TYPE="$2"
   DEVICE_PURPOSE="$3"
   local command
-  command=(dfx canister call internet_identity add "(${ANCHOR}, record { alias = \"\"; protection = variant { unprotected }; pubkey = blob \"${DEVICE_PUB_KEY_BLOB}\"; key_type = variant { ${DEVICE_KEY_TYPE} }; purpose = variant { ${DEVICE_PURPOSE} }; })" --network "$DFX_NETWORK")
+  command=(dfx canister call internet_identity add "(${ANCHOR}: nat64, record { alias = \"\"; protection = variant { unprotected }; pubkey = blob \"${DEVICE_PUB_KEY_BLOB}\"; key_type = variant { ${DEVICE_KEY_TYPE} }; purpose = variant { ${DEVICE_PURPOSE} }; })" --network "$DFX_NETWORK")
   "${command[@]}" >/dev/null
 }
 
