shellcheck

diff --git a/bin/test-readme b/bin/test-readme
--- a/bin/test-readme
+++ b/bin/test-readme
@@ -1,3 +1,49 @@
 #!/usr/bin/env bash
-set -euxo pipefail
-cat README.md | sed -En '/```bash/,/```/{/```/b;p}' | sed 's!https://github.com/!git@github.com:!g' | bash -euxo pipefail
+set -euo pipefail
+
+print_help() {
+  cat <<-EOF
+	Tests the commands in the README.
+
+	Usage: $(basename "$0") [flags]
+
+	Flags:
+	--help
+	  Prints this help text.
+
+	--ssh)
+	  Clones from github via ssh instead of https.
+	EOF
+}
+
+AUTH=http
+modify_auth() {
+  case "${AUTH:-}" in
+  ssh) sed 's!https://github.com/!git@github.com:!g' ;;
+  *) cat ;;
+  esac
+}
+
+while (($# > 0)); do
+  arg="$1"
+  shift 1
+  case "${arg:-}" in
+  --help)
+    print_help
+    exit 0
+    ;;
+  --ssh)
+    AUTH=ssh
+    ;;
+  *)
+    {
+      echo "ERROR: Unrecognized argument: ${arg:-}"
+      exit 1
+    } >&2
+    ;;
+  esac
+done
+
+# We really do want backticks.
+# shellcheck disable=SC2016
+sed <README.md -En '/```bash/,/```/{/```/b;p}' | sed 's!https://github.com/!git@github.com:!g' | bash -euxo pipefail
